import { useEffect, useMemo, useState } from 'react';
import type { ReactNode } from 'react';

type Summary = { requests: number; successRate: number; inputTokens: number; outputTokens: number; cacheRead: number; cacheWrite: number; p50Ttft: number | null; p95Ttft: number | null; p50Tps: number | null; p95Tps: number | null; totalCost: number | null };
type Request = { id: string; traceId: string; agentId: string; presetId: string; requestedModel: string; normalizedModel: string; billingModel: string; protocolIn: string; metrics: { ttfbMs: number | null; ttftMs: number | null; generationMs: number | null; durationMs: number | null; outputTps: number | null }; tokens: { inputUncached: number | null; cacheRead: number | null; cacheWrite: number | null; outputText: number | null; outputReasoning: number | null; quality: string }; status: string; cost: { totalApiCost: string | null }; usageConfidence: string; sanitizedErrorMessage: string | null };
type Agent = { id: string; name: string; type: string; version: string | null; enabled: boolean };
type Preset = { id: string; name: string; description: string | null; provider_id: string; requested_model: string; enabled: boolean };
type Provider = { id: string; name: string; vendor: string; base_url: string; protocol: string; enabled: boolean };
const api = <T,>(url: string): Promise<T> => fetch(url).then(async (r) => { if (!r.ok) throw new Error(`HTTP ${r.status}`); return await r.json() as T; });

export default function App() {
  const [tab, setTab] = useState('Overview'); const [summary, setSummary] = useState<Summary | null>(null); const [requests, setRequests] = useState<Request[]>([]); const [selected, setSelected] = useState<Request | null>(null);
  const reload = () => { api<Summary>('/api/summary').then(setSummary).catch(() => undefined); api<Request[]>('/api/requests').then(setRequests).catch(() => undefined); };
  useEffect(() => { reload(); const timer = setInterval(reload, 3000); return () => clearInterval(timer); }, []);
  const cards = useMemo(() => summary ? [['Requests', summary.requests], ['Success Rate', `${(summary.successRate * 100).toFixed(1)}%`], ['Input Tokens', summary.inputTokens], ['Output Tokens', summary.outputTokens], ['Cache Read', summary.cacheRead], ['Cache Write', summary.cacheWrite], ['Equivalent API Cost', summary.totalCost === null ? 'Unknown' : `$${summary.totalCost}`], ['P50/P95 TTFT', `${summary.p50Ttft ?? '—'} / ${summary.p95Ttft ?? '—'} ms`], ['P50/P95 TPS', `${summary.p50Tps ?? '—'} / ${summary.p95Tps ?? '—'}`]] : [], [summary]);
  const nav = ['Overview', 'Requests', 'Providers', 'Agents & Presets', 'Pricing', 'Diagnostics', 'Settings'];
  return <div className="shell"><aside><div className="brand"><span className="eye">◉</span><div><strong>Vision</strong><small>神之眼 · Control Plane</small></div></div>{nav.map((item) => <button className={tab === item ? 'nav active' : 'nav'} onClick={() => setTab(item)} key={item}>{item}</button>)}<div className="status"><span className="dot" /> Gateway 127.0.0.1:8787</div></aside><main><header><div><p className="eyebrow">PERSONAL LLM CONTROL PLANE</p><h1>{tab}</h1><p className="muted">先测量，再判断；先观察，再推荐。</p></div><button className="refresh" onClick={reload}>刷新数据</button></header>{tab === 'Overview' && <><section className="cards">{cards.map(([label, value]) => <div className="card" key={label}><span>{label}</span><strong>{value}</strong></div>)}</section><section className="panel"><div className="panel-title"><div><h2>Recent requests</h2><p>每个指标都能回溯到原始 Request。</p></div><button onClick={() => setTab('Requests')}>查看全部 →</button></div><RequestTable rows={requests.slice(0, 8)} onSelect={setSelected} /></section></>}{tab === 'Requests' && <section className="panel"><div className="panel-title"><div><h2>Request Explorer</h2><p>请求、Token、Timing、Cost 和可信度。</p></div></div><RequestTable rows={requests} onSelect={setSelected} /></section>}{tab === 'Diagnostics' && <Diagnostics />}{tab === 'Agents & Presets' && <AgentPresetPanel />}{tab === 'Providers' && <ProviderPanel />}{tab === 'Settings' && <SettingsPanel />}{tab === 'Pricing' && <section className="empty panel"><div className="big-icon">✦</div><h2>Pricing snapshots</h2><p>当前内置 Mock 快照；历史请求固定关联 pricing_snapshot_id。</p></section>}{selected && <RequestDrawer request={selected} onClose={() => setSelected(null)} />}</main></div>;
}

function RequestTable({ rows, onSelect }: { rows: Request[]; onSelect: (request: Request) => void }) { return <div className="table-wrap"><table><thead><tr><th>Status</th><th>Agent</th><th>Model</th><th>Protocol</th><th>Input</th><th>Output</th><th>TTFT</th><th>TPS</th><th>Cost</th></tr></thead><tbody>{rows.length === 0 ? <tr><td colSpan={9} className="muted center">还没有请求；向 http://127.0.0.1:8787/v1/responses 发送一个请求即可。</td></tr> : rows.map((request) => <tr key={request.id} onClick={() => onSelect(request)}><td><span className={`status-pill ${request.status}`}>{request.status}</span></td><td>{request.agentId}</td><td>{request.billingModel}</td><td>{request.protocolIn}</td><td>{request.tokens.inputUncached ?? '—'}</td><td>{request.tokens.outputText ?? '—'}</td><td>{request.metrics.ttftMs ?? '—'} ms</td><td>{request.metrics.outputTps ?? '—'}</td><td>{request.cost.totalApiCost === null ? 'Unknown' : `$${request.cost.totalApiCost}`}</td></tr>)}</tbody></table></div>; }
function RequestDrawer({ request, onClose }: { request: Request; onClose: () => void }) { return <div className="drawer"><button className="close" onClick={onClose}>×</button><h2>Request Detail</h2><dl><dt>Request ID</dt><dd>{request.id}</dd><dt>Trace ID</dt><dd>{request.traceId}</dd><dt>Agent / Preset</dt><dd>{request.agentId} / {request.presetId}</dd><dt>Models</dt><dd>{request.requestedModel} → {request.normalizedModel} → {request.billingModel}</dd><dt>Protocol</dt><dd>{request.protocolIn}</dd><dt>Timing</dt><dd>TTFB {request.metrics.ttfbMs ?? '—'} ms · TTFT {request.metrics.ttftMs ?? '—'} ms · Generation {request.metrics.generationMs ?? '—'} ms · TPS {request.metrics.outputTps ?? '—'}</dd><dt>Tokens</dt><dd>input {request.tokens.inputUncached ?? '—'} · output {request.tokens.outputText ?? '—'} · reasoning {request.tokens.outputReasoning ?? '—'} · cache read {request.tokens.cacheRead ?? '—'} · cache write {request.tokens.cacheWrite ?? '—'}</dd><dt>Quality / Confidence</dt><dd><span className="badge">{request.tokens.quality}</span> <span className="badge">{request.usageConfidence}</span></dd><dt>Cost</dt><dd>{request.cost.totalApiCost === null ? 'Unknown' : `$${request.cost.totalApiCost}`}</dd>{request.sanitizedErrorMessage && <><dt>Error</dt><dd className="error">{request.sanitizedErrorMessage}</dd></>}</dl></div>; }
function EntityTable({ headers, rows }: { headers: string[]; rows: ReactNode[][] }) { return <div className="table-wrap"><table><thead><tr>{headers.map((header, index) => <th key={`${header}-${index}`}>{header}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={index}>{row.map((cell, cellIndex) => <td key={cellIndex}>{cell}</td>)}</tr>)}</tbody></table></div>; }
function AgentPresetPanel() { const [agents, setAgents] = useState<Agent[]>([]); const [presets, setPresets] = useState<Preset[]>([]); const reload = () => { api<Agent[]>('/api/agents').then(setAgents); api<Preset[]>('/api/presets').then(setPresets); }; useEffect(reload, []); const add = async (kind: 'agent' | 'preset') => { const name = window.prompt(`${kind} name`); if (!name) return; const id = name.toLowerCase().replace(/[^a-z0-9]+/g, '-'); const body = kind === 'agent' ? { id, name, type: 'custom', version: '1' } : { id, name, providerId: 'mock', requestedModel: 'vision-mock-1' }; await fetch(`/api/${kind === 'agent' ? 'agents' : 'presets'}`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }); reload(); }; const remove = async (kind: 'agents' | 'presets', id: string) => { await fetch(`/api/${kind}/${encodeURIComponent(id)}`, { method: 'DELETE' }); reload(); }; return <section className="panel"><div className="panel-title"><div><h2>Agents & Presets</h2><p>本地 CRUD；Gateway 通过 X-Vision-Agent / X-Vision-Preset 关联请求。</p></div><div><button onClick={() => add('agent')}>新增 Agent</button> <button onClick={() => add('preset')}>新增 Preset</button></div></div><EntityTable headers={['Agent', 'Type', 'Version', 'Enabled', '']} rows={agents.map((agent) => [<><strong>{agent.name}</strong><small>{agent.id}</small></>, agent.type, agent.version ?? '—', agent.enabled ? 'yes' : 'no', <button onClick={() => remove('agents', agent.id)} key="remove">删除</button>])} /><EntityTable headers={['Preset', 'Description', 'Provider', 'Model', '']} rows={presets.map((preset) => [<><strong>{preset.name}</strong><small>{preset.id}</small></>, preset.description ?? '—', preset.provider_id, preset.requested_model, <button onClick={() => remove('presets', preset.id)} key="remove">删除</button>])} /></section>; }
function ProviderPanel() { const [providers, setProviders] = useState<Provider[]>([]); useEffect(() => { api<Provider[]>('/api/providers').then(setProviders); }, []); return <section className="panel"><div className="panel-title"><div><h2>Providers</h2><p>凭据仅通过 credential_ref 关联；普通 Provider 表不保存 Secret。</p></div></div><EntityTable headers={['Name', 'Vendor', 'Base URL', 'Protocol', 'Enabled']} rows={providers.map((provider) => [<><strong>{provider.name}</strong><small>{provider.id}</small></>, provider.vendor, provider.base_url, provider.protocol, provider.enabled ? 'yes' : 'no'])} /></section>; }
function SettingsPanel() { const [mode, setMode] = useState<'normal' | 'privacy' | 'debug'>('normal'); const [retention, setRetention] = useState<'24h' | '7d' | '30d'>('7d'); useEffect(() => { api<{ mode: 'normal' | 'privacy' | 'debug'; retention: '24h' | '7d' | '30d' | null }>('/api/privacy').then((config) => { setMode(config.mode); if (config.retention) setRetention(config.retention); }); }, []); const save = async () => { const response = await fetch('/api/privacy', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ mode, retention: mode === 'debug' ? retention : null }) }); if (!response.ok) window.alert(((await response.json()) as { error?: string }).error ?? '保存失败'); }; return <section className="panel"><div className="panel-title"><div><h2>Privacy</h2><p>默认 Normal：仅保存指标、哈希和脱敏错误，不保存完整 Prompt/Response。</p></div></div><label>Mode <select value={mode} onChange={(event) => setMode(event.target.value as typeof mode)}><option value="normal">Normal</option><option value="privacy">Privacy</option><option value="debug">Debug（主动开启）</option></select></label>{mode === 'debug' && <label>Retention <select value={retention} onChange={(event) => setRetention(event.target.value as typeof retention)}><option value="24h">24h</option><option value="7d">7d</option><option value="30d">30d</option></select></label>}<button onClick={save}>保存隐私配置</button>{mode === 'debug' && <p className="warning">Debug 会允许保存脱敏调试数据，并按 retention 清理；不要在共享环境开启。</p>}</section>; }
function Diagnostics() { const [checks, setChecks] = useState<Array<{ name: string; message: string; result: string; durationMs: number }>>([]); const run = () => api<Array<{ name: string; message: string; result: string; durationMs: number }>>('/api/diagnostics').then(setChecks); useEffect(() => { run(); }, []); return <section className="panel"><div className="panel-title"><div><h2>Diagnostics</h2><p>真实核心模块的运行检查。</p></div><button onClick={run}>Run Full Diagnostic</button></div>{checks.map((check) => <div className="check" key={check.name}><span className={`check-icon ${check.result}`}>{check.result === 'passed' ? '✓' : '!'}</span><div><strong>{check.name}</strong><small>{check.message} · {check.durationMs} ms</small></div><span className={check.result === 'passed' ? 'passed' : 'error'}>{check.result}</span></div>)}</section>; }
