import http from 'node:http';
import { calculateCost, classifyMeaningfulEvent, createRequest, deriveMetrics, newId, normalizeTokens, redact, sha256, nowIso, Observation } from './core.js';
import { VisionStore } from './storage.js';
import { runDiagnostics } from './diagnostics.js';
import { replayFixture } from './replay.js';

export interface GatewayOptions { port?: number; upstream?: string; store?: VisionStore; }
export function startGateway(options: GatewayOptions = {}): http.Server {
  const store = options.store ?? new VisionStore(); store.seed(); const upstream = options.upstream ?? 'http://127.0.0.1:8790';
  const visiondUrl = (process.env.VISIOND_URL ?? '').replace(/\/$/, '');
  const replicate = async (path: string, value: unknown): Promise<void> => {
    if (!visiondUrl) return;
    try { await fetch(`${visiondUrl}${path}`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(redact(value)) }); }
    catch { /* sidecar is optional during local fallback and is diagnosed separately */ }
  };
  const server = http.createServer(async (req, res) => {
    if (req.method === 'GET' && req.url === '/health') { res.writeHead(200, { 'content-type': 'application/json' }).end(JSON.stringify({ ok: true, name: 'Vision Gateway' })); return; }
    if (req.method === 'GET' && req.url === '/api/summary') { json(res, store.summary()); return; }
    if (req.method === 'GET' && req.url?.startsWith('/api/requests')) { json(res, store.listRequests()); return; }
    if (req.method === 'GET' && req.url === '/api/providers') { json(res, store.listProviders()); return; }
    if (req.method === 'GET' && req.url === '/api/agents') { json(res, store.listAgents()); return; }
    if (req.method === 'GET' && req.url === '/api/presets') { json(res, store.listPresets()); return; }
    if (req.method === 'GET' && req.url === '/api/privacy') { json(res, store.getPrivacyConfig()); return; }
    if (req.method === 'POST' && req.url === '/api/privacy') { try { const body = JSON.parse(await readBody(req)) as { mode?: 'normal' | 'privacy' | 'debug'; retention?: '24h' | '7d' | '30d' | null }; if (!body.mode || !['normal', 'privacy', 'debug'].includes(body.mode)) throw new Error('mode must be normal, privacy or debug'); store.setPrivacyConfig(body.mode, body.retention ?? null); json(res, store.getPrivacyConfig()); } catch (error) { json(res, { error: error instanceof Error ? error.message : 'invalid privacy config' }, 400); } return; }
    if (req.method === 'POST' && req.url === '/api/agents') { const body = JSON.parse(await readBody(req)) as { id?: string; name?: string; type?: string; version?: string; metadata?: Record<string, unknown>; enabled?: boolean }; if (!body.id || !body.name || !body.type) { json(res, { error: 'id, name and type are required' }, 400); return; } store.saveAgent({ id: body.id, name: body.name, type: body.type, version: body.version, metadata: body.metadata, enabled: body.enabled }); json(res, { ok: true }); return; }
    if (req.method === 'DELETE' && req.url?.startsWith('/api/agents/')) { store.deleteAgent(decodeURIComponent(req.url.slice('/api/agents/'.length))); json(res, { ok: true }); return; }
    if (req.method === 'POST' && req.url === '/api/presets') { const body = JSON.parse(await readBody(req)) as { id?: string; name?: string; description?: string; providerId?: string; requestedModel?: string; routingPolicy?: Record<string, unknown>; config?: Record<string, unknown>; enabled?: boolean }; if (!body.id || !body.name || !body.providerId || !body.requestedModel) { json(res, { error: 'id, name, providerId and requestedModel are required' }, 400); return; } store.savePreset({ id: body.id, name: body.name, description: body.description, providerId: body.providerId, requestedModel: body.requestedModel, routingPolicy: body.routingPolicy, config: body.config, enabled: body.enabled }); json(res, { ok: true }); return; }
    if (req.method === 'DELETE' && req.url?.startsWith('/api/presets/')) { store.deletePreset(decodeURIComponent(req.url.slice('/api/presets/'.length))); json(res, { ok: true }); return; }
    if (req.method === 'GET' && req.url === '/api/diagnostics') { json(res, await runDiagnostics(store)); return; }
    if (req.method === 'POST' && req.url === '/api/replay') { const body = await readBody(req); const input = JSON.parse(body) as { fixture?: string }; const fixture = input.fixture ?? 'fixtures/responses/simple'; json(res, await replayFixture(fixture, store)); return; }
    if (req.method !== 'POST' || req.url !== '/v1/responses') { res.writeHead(404).end(); return; }
    const body = await readBody(req); let payload: Record<string, unknown>;
    try { payload = JSON.parse(body) as Record<string, unknown>; } catch { json(res, { error: { type: 'invalid_json', message: 'Request body must be JSON' } }, 400); return; }
    const requestedModel = typeof payload.model === 'string' ? payload.model : 'vision-mock-1'; const isStreaming = payload.stream === true; const receivedAtMs = Date.now();
    const record = createRequest({ requestedModel, normalizedModel: requestedModel, billingModel: requestedModel, isStreaming, requestHash: sha256(JSON.stringify(redact(payload))), nativeRequestId: typeof payload.id === 'string' ? payload.id : null, agentId: header(req, 'x-vision-agent') ?? 'unknown', presetId: header(req, 'x-vision-preset') ?? 'unknown', traceId: header(req, 'x-vision-trace-id') ?? newId('trace') });
    const obs: Observation = { observationId: newId('obs'), logicalRequestId: record.logicalRequestId, source: 'vision_proxy', confidence: 'high', capturedAt: nowIso(), rawSchemaVersion: 'vision-observation-v1', metrics: { receivedAt: record.receivedAt }, metadata: { protocol: 'openai-responses', streaming: isStreaming }, payloadHash: record.requestHash }; store.addObservation(obs); await replicate('/api/observations', obs);
    record.upstreamStartedAt = nowIso(); const upstreamStartedMs = Date.now();
    try {
      const upstreamResponse = await fetch(`${upstream}/v1/responses`, { method: 'POST', headers: { 'content-type': 'application/json' }, body });
      record.firstByteAt = nowIso(); const firstByteMs = Date.now(); record.statusCode = upstreamResponse.status;
      if (!upstreamResponse.ok || !upstreamResponse.body) { const text = await upstreamResponse.text(); record.status = upstreamResponse.status >= 500 ? 'error' : 'error'; record.errorType = upstreamResponse.status === 429 ? 'rate_limit' : 'upstream_error'; record.errorCode = String(upstreamResponse.status); record.sanitizedErrorMessage = `Upstream request failed (${upstreamResponse.status})`; record.completedAt = nowIso(); record.metrics = deriveMetrics({ upstreamStartedAt: upstreamStartedMs, firstByteAt: firstByteMs, firstMeaningfulOutputAt: null, completedAt: Date.now() }, null); record.finalizedAt = nowIso(); store.saveRequest(record); await replicate('/api/requests', record); json(res, { error: { type: record.errorType, code: record.errorCode, message: record.sanitizedErrorMessage, detail: String(redact(text)) } }, upstreamResponse.status); return; }
      if (!isStreaming) { const text = await upstreamResponse.text(); const data = JSON.parse(text) as Record<string, unknown>; const usage = data.usage as Record<string, unknown> | undefined; record.tokens = normalizeTokens(usage); record.usageSource = usage ? 'provider_usage' : 'missing'; record.usageConfidence = usage ? 'high' : 'unknown'; record.responseHash = sha256(text); record.completedAt = nowIso(); record.status = 'success'; record.metrics = deriveMetrics({ upstreamStartedAt: upstreamStartedMs, firstByteAt: firstByteMs, firstMeaningfulOutputAt: firstByteMs, completedAt: Date.now() }, (record.tokens.outputText ?? 0) + (record.tokens.outputReasoning ?? 0)); finalizeCost(record, store); record.finalizedAt = nowIso(); store.saveRequest(record); await replicate('/api/requests', record); json(res, data, upstreamResponse.status); return; }
      res.writeHead(upstreamResponse.status, { 'content-type': 'text/event-stream', 'cache-control': 'no-cache', connection: 'keep-alive' }); let buffer = ''; let firstMeaningful: number | null = null; let lastUsage: Record<string, unknown> | undefined; const reader = upstreamResponse.body.getReader();
      try { while (true) { const part = await reader.read(); if (part.done) break; const chunk = Buffer.from(part.value).toString('utf8'); if (record.firstByteAt === null) record.firstByteAt = nowIso(); res.write(chunk); buffer += chunk; const lines = buffer.split(/\r?\n/); buffer = lines.pop() ?? ''; for (const line of lines) { if (!line.startsWith('data: ') || line.slice(6) === '[DONE]') continue; try { const event = JSON.parse(line.slice(6)) as Record<string, unknown>; record.chunkCount++; if (classifyMeaningfulEvent(event) && firstMeaningful === null) firstMeaningful = Date.now(); if (event.usage && typeof event.usage === 'object') lastUsage = event.usage as Record<string, unknown>; } catch { /* malformed provider event is captured by final status */ } } } record.status = 'success'; } catch (error) { record.status = 'aborted'; record.errorType = 'stream_interrupted'; record.sanitizedErrorMessage = error instanceof Error ? error.message.replace(/https?:\/\/\S+/g, '[URL]') : 'stream interrupted'; } finally { reader.releaseLock(); res.end(); }
      record.firstMeaningfulOutputAt = firstMeaningful ? new Date(firstMeaningful).toISOString() : null; record.tokens = normalizeTokens(lastUsage); record.usageSource = lastUsage ? 'provider_usage' : 'missing'; record.usageConfidence = lastUsage ? 'high' : 'unknown'; record.completedAt = nowIso(); record.metrics = deriveMetrics({ upstreamStartedAt: upstreamStartedMs, firstByteAt: firstByteMs, firstMeaningfulOutputAt: firstMeaningful, completedAt: Date.now() }, (record.tokens.outputText ?? 0) + (record.tokens.outputReasoning ?? 0)); record.responseHash = sha256(`${record.traceId}:${record.chunkCount}`); finalizeCost(record, store); record.finalizedAt = nowIso(); store.saveRequest(record); await replicate('/api/requests', record);
    } catch (error) { record.status = 'error'; record.errorType = 'gateway_error'; record.sanitizedErrorMessage = error instanceof Error ? error.message : 'gateway error'; record.completedAt = nowIso(); record.finalizedAt = nowIso(); store.saveRequest(record); await replicate('/api/requests', record); json(res, { error: { type: 'gateway_error', message: 'Vision could not reach the provider' } }, 502); }
  }); server.listen(options.port ?? 8787, '127.0.0.1'); return server;
}
function finalizeCost(record: ReturnType<typeof createRequest>, store: VisionStore): void { const pricing = store.findPricing(record.providerId, 'mock-model', record.receivedAt); if (!pricing) { record.pricingSource = 'unknown'; return; } record.pricingSnapshotId = pricing.id; record.pricingSource = pricing.source; record.cost = calculateCost(record.tokens, pricing); }
function readBody(req: http.IncomingMessage): Promise<string> { return new Promise((resolve, reject) => { const chunks: Buffer[] = []; req.on('data', c => chunks.push(Buffer.from(c))); req.on('end', () => resolve(Buffer.concat(chunks).toString('utf8'))); req.on('error', reject); }); }
function header(req: http.IncomingMessage, name: string): string | null { const v = req.headers[name]; return Array.isArray(v) ? v[0] ?? null : v ?? null; }
function json(res: http.ServerResponse, value: unknown, status = 200): void { res.writeHead(status, { 'content-type': 'application/json' }).end(JSON.stringify(value)); }
